### ISSUE TITLE
Management - Establish First Proposal Managers

### ISSUE THREAD

**Issue by cl-tim** [aggregatedfinance/agfi-dao#1]
_The modification to be made (e.g. add new DAO proposer):_

Selecting the first DAO proposers.

_The purpose of the modification, and a justification as to requiring the modification to be made:_

Congruent Labs as DAO Custodian will not act as proposal managers for the project. A starting cohort of 5 others to join the role of proposal manager is needed to establish the DAO management. Duties for this role include:

1. Actively managing these Github issues (removing spam, invalid requests, etc.)
2. From diverse timezones. We don't want every proposal manager living within a single timezone.
3. Willing to pay gas to create proposals using the DAO Governance dashboard.

Individuals requesting consideration for being accepted into this role must provide their Github username, their wallet address, their timezone, and an explanation as to why they are suitable as a Proposal Manager into the comments of this post.

Future proposals may request to remove anyone in the role of Proposal Manager if they believe they are underperforming in their duties.

**Comment by AGFITRUST** [comment]
What is the job for proposal manager?
If I can help, why not.
Love this project

**Comment by cl-tim** [comment]
> What is the job for proposal manager?
> If I can help, why not.
> Love this project

Just moving proposals to release by the treasury once a vote passes, and moderation of these issues on github

**Comment by AGFITRUST** [comment]
OK thanks, if you need, I'm available. My businesses are autonomous and don't take me too much time.
In the Philippines time actually, if the time is good for you.

Regards, Anthony

**Comment by Melkorious** [comment]
Melkor here (On Twitter as @Melkorious, On Telegram as @Elevented)

I'd like to be considered for the role of Proposal Manager.

I joined the AGFI community in December, 2021 - and have been active ever since.  I've hosted AMA's, written content for the project on various fronts, helped manage various deliverables, and I have remained a consistent voice in the community throughout.

As a Proposal Manager, I will be sure to evaluate Proposals objectively and without bias.  I'll consider the holistic risk/reward associated with submitted Proposals - and will actively articulate any concerns, especially against Proposals that may place the project or its interests at peril.

I commit to remaining an active participant in the AGFI DAO, in general.

Thank you for your consideration!

- Melkor

**Comment by Cryptobuzz1** [comment]
Hi its aden, as seen on community telegram cryptobuzz.

Please accept this statement of my intention of becoming a proposal manager of the agfi dao.

Have spent time with the comunitee from january 3rd 2022. My initial investment has grown and proud to be a part of the new AAA group  

As most personel are well aware in crypto you fall in love with projects and I have done exactly  this with agfi. Due to the level of commitment I have towards the project I believe this will give me the better judgement of proposals to help succeed the project further and also be able to judge on the proposals of which try and sabotage and hurt the project.

Please accept this as my application to become a proposal manager of the agfi dao. I will give it 100% and it has my heart as always  

Regards Aden 

Telegram @adencryptobuzz

**Comment by cl-tim** [comment]
Thanks for your submissions people. Just to remind you of the proposal reqs, you need to provide your wallet address and your timezone for the proposal. The wallet address is needed for delegating the proposer role once the vote passes.

And timezone is just there so we can see if there are significant TZ gaps that need to be filled. Minimum one from Asia, one from Europe, and one from the Americas - that way someone is always awake.

The wallet address doesn't need to hold AGFI if you want to separate that out to a different wallet. But it will need a little ETH for gas when interacting with the DAO.

**Comment by AGFITRUST** [comment]
AGFITRUST
0xd6AE38813c3346F1F393D16F11E52CdF6cCB8271
Philippines / Asia

**Comment by sicaria-eth** [comment]
Hey guys it’s Aria! When I first joined the Aggregated Finance community in 2021, it was an extremely exciting project and community full of brilliant, aspiring individuals that I couldn’t wait to be a part of. Today, that statement could not hold more true, which is why I want to be considered to act as a Proposal Manager.

I would be an asset to the Aggregated Finance community due to 3 main reasons. 
First, I will maintain an objective, fair viewpoint on all proposals.  
Second, I have ample amounts of freetime due to the nature of my real life responsibilities. I will be able to sort through proposals in a timely manner. 
Lastly, My moral compass is strong and I am utilitarian in nature. I believe that alone ape is weak; together ape is strong!


Telegram: Sicaria_eth
Github: Sicaria-eth
Wallet: 0xABE9F6f05f4189886feC9E5dDD69f40BB9b8F5fe

Time zone
North America
GMT -5

**Comment by CryptoNielsB** [comment]
Hi all, NielsB from the Telegram here!

Joined AGFI in 2021 around it's supreme run towards ATH! Very excited for the future, together with all who belongs to it's community. I could be able to cover some Europe times as a PM, to maintain some proposals. 
I'm always learning, and willing to help whereever i could. Will give my honest opinion, and as a team, we could definitely manage these proposals the right way!

Telegram: @Nielscrypto
Github: CryptoNielsB
Wallet: 0x8910F137687F9290D822219bF0CeDD76eC65A09b
Time zone: Europe (GMT+2)

**Comment by Crypto1HK** [comment]
Crypto1HK on github, Crypto1kai on twitter and tg
0xbcafaD74ee5128cBAA846075198D1FC54cd9c84B
Hi Community.  I'm keen to be involved if any of my skills transfer and you'll have me. Tradfi adviser by day and passionate defi investor and crypto enthusiast since 2017.  Small business owner with a degree in finance from way back.  Happy to cast my eye over proposals with an objective or at least pragmatic intent.  
Agfi is my #1

**Comment by IgorBogdanoff420** [comment]
Igor like to be considered for PM.

Timezone: GMT
Wallet: igor-bogdanoff.eth
CV: Igor is Igor

**Comment by cl-tim** [comment]
As no objections to the above proposers have been raised, opening proposal on chain for the 7 proposers:

GitHub Username: Melkorious
Address: 0xDcDd54798393A90d7c9379536b30C5F5Af1dD9D1
TZ: UTC-4

GitHub Username: Cryptobuzz1
Address: 0xee8ee11F288a73D0015975feab2Ca05d7CfF3613
TZ: UTC+1

GitHub Username: AGFITRUST
Address: 0xd6AE38813c3346F1F393D16F11E52CdF6cCB8271
TZ: UTC+8

GitHub Username: Sicaria-eth
Address: 0xABE9F6f05f4189886feC9E5dDD69f40BB9b8F5fe
TZ: UTC-5

GitHub Username: CryptoNielsB
Address: 0x8910F137687F9290D822219bF0CeDD76eC65A09b
TZ: UTC+2

GitHub Username: Crypto1HK
Address: 0xbcafaD74ee5128cBAA846075198D1FC54cd9c84B
TZ: UTC+8 (estimated, user provided only "Asia")

GitHub Username: IgorBogdanoff420
Address: 0xef333de85f5409cd644ed6602f604a0077f1d153 (resolved from igor-bogdanoff.eth)
TZ: UTC

**Comment by AGFITRUST** [comment]
Thanks for your trust, I'm really excited to be an active part of this very promising project.

Regards all, Anthony

**Comment by aggregatedfinance** [comment]
Proposal reopened now that more holders have delegated their votes, and includes a reduction in voting period to 72 hours to speed up future votes: https://www.tally.xyz/proposal/c3f1fa45-0ae1-4d53-a20c-fc964ab0d794

**Comment by cl-tim** [comment]
The proposal has been executed, and all proposal managers have been delegated as collaborators on GitHub and granted Canceller roles for DAO protection:

https://etherscan.io/tx/0xfd326bcf7b9678d61ec10809ab88aba20bff00a0e70deb6ca57b6177cb471e56
https://etherscan.io/tx/0x379861a89f9dd7a0bca7ef9f0d04b151aac25e7267f3eacfe1b16cde76f60981
https://etherscan.io/tx/0x99ba96da318b806556aa4714d37b55acd4784a1ed931ef211bc606319294b084
https://etherscan.io/tx/0x361f6f583a2127d2ca36654a1d26da0efa5ebfb94d4848fa880ec479948c3653
https://etherscan.io/tx/0xf4528f3fe4f12fa42a1f40cbe5971b2869cf45e5c965be48a2e0c49ec8385a44
https://etherscan.io/tx/0xea15943472ad25cd3747f15a9a01381aac620eec4d6755ed82be97687fb7b9f4
https://etherscan.io/tx/0x4a77e2acbd24f3be27cc11f9cc5b4ac8b2c1c6749a7b978ccd6689e9fdb48604

This transaction was an accidental duplicate of the first, and can be disregarded:

https://etherscan.io/tx/0x33f80d3fbb18aab6487afc82a627f4ac46dce46a6ad18404e6f780895f747e25

**Comment by cl-tim** [comment]
Proposal managers - check your email to accept the invites to this repository

**Comment by AGFITRUST** [comment]
Done, thanks

**Comment by Melkorious** [comment]
Done!

On Jul 7, 2022, at 12:17 AM, AGFITRUST ***@***.***> wrote:

﻿
Done, thanks
