### ISSUE TITLE
Treasury - $QNT

### ISSUE THREAD

**Issue by IgorBogdanoff420** [aggregatedfinance/agfi-dao#6]
Igor would like to propose placing $15000 of our treasury into Quant Network at the market price at the point the vote closes, should the community vote for it. $QNT is working its way to blue-chip status and Igor feels any money parked in there is unlikely to lose value against BTC, ETH or the dollar, over a 2-5 year period.

Igor feels with a small treasury we require a long time-horizon to build AGFI's treasury into something that can really make an impact and investing in strong, established coins can supplement our farming activities.

**Comment by AGFITRUST** [comment]
Great idea! 
d
Do you want to make the proposal or somebody do it explaining us how and we all learn better how to do?
Regards

**Comment by Cryptobuzz1** [comment]
I agree with your idea 15k but I would ask for 25k 
15k first investment on Qnt if the token takes a 30% drop you have 5k to dca and if drops 30% again toy still have 5k to dca bringing origional entry down.

However if the coin never decreases in value the 10k for dca never gets used . I'd.prefer a back up plan 

Would we need the contract address for.QNT.
Which part of the treasury would be used I.e the eth holdings or the dai?

As for the treasury I think.its a good risk to management more potential than holding stables and you are being wise only asking for apx 18% of the treasury value to invest with

**Comment by Peertosh** [comment]
Who will decided when to sell QNT?  Is it also a proposal for example after a 50% pump?

**Comment by LeoKing7777** [comment]
I think the proposal to invest into any blue chip coin potential like QNT or event MATIC polygon is great.BUT, we need to dig into the market sentiment and ask expert traders and macro analysts to make that call and ensure that we don't fall into a fake crypto Pump and end up in a blood bath again in August/September. We really need a extra farmer or trader than can help us make these decisions that can be a lot more hands to manage this. We can give a portion of the treasury with say 25k ? I.e even if buying QNT, they could then sell during a good pump and then re-buy the dip- rinse and repeat just to be on the safe side. Usually if they see a strong overbought signal he/she could sell our position to then await a much lower entry point which we wouldn’t be able to execute or react to as quickly with a DAO proposal.


OR - rather than putting 15k into QNT I would rather diversify and add 25k into a few blue chip potentials like - MATIC/ETH/ADA/QNT/SOL all 5k each - but not yet, as we just missed a good pump.

The question is what new traders/farmer candidates,do we know that are trustworthy and have a credible background, while also not being so overpriced that we can approach to hire ? We have 100bn token of AGFI and sure we can use them to distribute for on target payments and performance.

**Comment by Cryptobuzz1** [comment]
I agree with expert advice, I also look at law of averages and history
suggest an 80% correction is normally bottom so there is potential of more
blood but if you have the back up in place to dca this investment has
potential.

A bottom is near. Potentially already had it. The big issue to me is war.
If this was to cease you have to be ready to deploy.

Maybe zack may have a few words. I've noticed commodities have all had apx
20% corrections from highs this will filter into inflation figures poss
sept defo oct 22.

**Comment by tradenews69** [comment]
too bad we didn't get in closer to the bottom. there could be a pullback in near term depending on BTC and ETH.

**Comment by LeoKing7777** [comment]
I think we are seeing a pull back now, maybe another crash is coming ? Maybe not, which is why I think we should revise this proposal an create an entry point and sell point rather then buying and having to wait for another proposal to sell it that takes at least 48 hrs to execute. Even if we are looking at having this long term - then the sentiment is there and there may be another crash in the near future - maybe a 20% reduction in current price could be our target entry? Either way we do need a buy and exit plan.

**Comment by aggregatedfinance** [comment]
Vote performed on Snapshot: https://snapshot.org/#/aggregatedfinance.eth/proposal/0x24c9f59b92022aedf148652c5cea7ddda9478feb64e01b928cf4951cff7dea55

Vote failed.
